<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All notifications have been deleted.' => 'Todas as notificações foram apagadas',
    'All notifications have been marked as read.' => 'Todas as notificações foram lidas',
    'Delete all' => 'Apagar tudo',
    'Mark all as read' => 'Ler todas',
    'Mark as read' => 'Marcar como lida',
    'Notifications' => 'Notificações',
    'Read' => 'Lida',
    'No notifications found' => '<i class="fa fa-3x fa-bell-o" aria-hidden="true"></i><br><h5>Não existem notificações</h5>',
    'There are no notifications to show' => 'Não existem notificações',
    'View all' => 'Ver todas',
    'a moment' => 'um momento',
    'ago' => 'atrás',
    '{n, plural, one{one day} other{# days}}' => '{n, plural, one{um dia} other{# dias}}',
    '{n, plural, one{one hour} other{# hours}}' => '{n, plural, one{uma hora} other{# horas}}',
    '{n, plural, one{one minute} other{# minutes}}' => '{n, plural, one{um minuto} other{# minutos}}',
    '{n, plural, one{one month} other{# months}}' => '{n, plural, one{um mês} other{# meses}}',
    '{n, plural, one{one second} other{# seconds}}' => '{n, plural, one{um segundo} other{# segundos}}',
    '{n, plural, one{one week} other{# weeks}}' => '{n, plural, one{uma semana} other{# semanas}}',
    '{n, plural, one{one year} other{# years}}' => '{n, plural, one{um ano} other{# anos}}',
];
